<a href="https://colab.research.google.com/github/Caio2909/Dados/blob/main/occupations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

users= pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|", index_col="user_id")
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [100]:
userMeanAge = users.groupby("occupation").mean(True)
userMeanAge

                     age
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

In [110]:
gender_ocup = users.groupby(['occupation','gender']).agg({'gender':'count'})
occup_count = users.groupby(['occupation']).agg('count')
occup_gener = gender_ocup.div(occup_count, level='occupation') * 100
occup_gener.loc[:, 'gender']

occupation     gender
administrator  F          45.569620
               M          54.430380
artist         F          46.428571
               M          53.571429
doctor         M         100.000000
educator       F          27.368421
               M          72.631579
engineer       F           2.985075
               M          97.014925
entertainment  F          11.111111
               M          88.888889
executive      F           9.375000
               M          90.625000
healthcare     F          68.750000
               M          31.250000
homemaker      F          85.714286
               M          14.285714
lawyer         F          16.666667
               M          83.333333
librarian      F          56.862745
               M          43.137255
marketing      F          38.461538
               M          61.538462
none           F          44.444444
               M          55.555556
other          F          34.285714
               M          65.714286
programmer     F           9.090909
               M          90.909091
retired        F           7.142857
               M          92.857143
salesman       F          25.000000
               M          75.000000
scientist      F           9.677419
               M          90.322581
student        F          30.612245
               M          69.387755
technician     F           3.703704
               M          96.296296
writer         F          42.222222
               M          57.777778
Name: gender, dtype: float64

In [99]:
maleRatio = users.groupby("occupation")
maleRatio = maleRatio['gender'].apply(lambda x: (x == "M").mean()*100).sort_values(ascending=False).round(1)
femaleRatio = 100 - maleRatio
maleRatio
ratios= {'M': maleRatio,'F': femaleRatio }
MFRatio = pd.DataFrame(ratios)
MFRatio

                   M     F
occupation
doctor         100.0   0.0
engineer        97.0   3.0
technician      96.3   3.7
retired         92.9   7.1
programmer      90.9   9.1
executive       90.6   9.4
scientist       90.3   9.7
entertainment   88.9  11.1
lawyer          83.3  16.7
salesman        75.0  25.0
educator        72.6  27.4
student         69.4  30.6
other           65.7  34.3
marketing       61.5  38.5
writer          57.8  42.2
none            55.6  44.4
administrator   54.4  45.6
artist          53.6  46.4
librarian       43.1  56.9
healthcare      31.2  68.8
homemaker       14.3  85.7

In [47]:
minMax = users.groupby("occupation").age.agg(["min", "max"])
minMax

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

In [88]:
userMeanAgeGender = users.groupby(["occupation","gender"]).age.mean(True)
userMeanAgeGender

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64