<a href="https://colab.research.google.com/github/Caio2909/Dados/blob/main/studentAlcohol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv')

df = df.loc[:,:'guardian']
cap = lambda x: x.capitalize()
def majority(x):
  if x > 17:
    return True
  return False
df['Mjob'] = df["Mjob"].apply(cap)
df['Fjob'] = df['Fjob'].apply(cap)
df['legalDrinker'] = df['age'].apply(majority)
def times10(x):
    if type(x) is int:
      return x*10
    return x

df.map(times10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legalDrinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,mother,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,course,father,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,other,mother,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,home,mother,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,course,other,True
391,MS,M,170,U,LE3,T,30,10,Services,Services,course,mother,False
392,MS,M,210,R,GT3,T,10,10,Other,Other,course,other,True
393,MS,M,180,R,LE3,T,30,20,Services,Other,course,mother,True
394,MS,M,190,U,LE3,T,10,10,Other,At_home,course,father,True